force-app/main/default/objects/DocDtl__c/fields/DocTyp__c.field-meta.xml
<CustomField>
    <fullName>DocTyp__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Additional documents</fullName>
            </value>
            <value>
                <fullName>Address Proof</fullName>
            </value>
            <value>
                <fullName>Address Proof (Residential)</fullName>
            </value>
            <value>
                <fullName>Audit Report (with schedules)</fullName>
            </value>
            <value>
                <fullName>Bank Statement</fullName>
            </value>
            <value>
                <fullName>Bureau Report</fullName>
            </value>
            <value>
                <fullName>CAM Report</fullName>
            </value>
            <value>
                <fullName>Charge Creation Documents</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Collateral Visit Photographs</fullName>
            </value>
            <value>
                <fullName>Constitution wise Mandatory documents</fullName>
            </value>
            <value>
                <fullName>Constitution wise Mandatory KYC documents</fullName>
            </value>
            <value>
                <fullName>CPV Documents</fullName>
            </value>
            <value>
                <fullName>CPV Photos</fullName>
            </value>
            <value>
                <fullName>DD</fullName>
            </value>
            <value>
                <fullName>Disbursal Documents</fullName>
            </value>
            <value>
                <fullName>Disbursement Memo</fullName>
            </value>
            <value>
                <fullName>DOB Proof</fullName>
            </value>
            <value>
                <fullName>Financials - P&amp;L and BL</fullName>
            </value>
            <value>
                <fullName>Form 16</fullName>
            </value>
            <value>
                <fullName>Form 26 AS</fullName>
            </value>
            <value>
                <fullName>Form 60</fullName>
            </value>
            <value>
                <fullName>General Insurance documents</fullName>
            </value>
            <value>
                <fullName>GST Returns</fullName>
            </value>
            <value>
                <fullName>Identity Proof</fullName>
            </value>
            <value>
                <fullName>Income Tax Returns</fullName>
            </value>
            <value>
                <fullName>Increments/ Appraisal Letter</fullName>
            </value>
            <value>
                <fullName>ITR Computation</fullName>
            </value>
            <value>
                <fullName>Legal Verification</fullName>
            </value>
            <value>
                <fullName>Life Insurance documents</fullName>
            </value>
            <value>
                <fullName>Sanction Letter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocMstr__c/fields/DocTyp__c.field-meta.xml
<CustomField>
    <fullName>DocTyp__c</fullName>
    <label>DocumentType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Address Proof</fullName>
            </value>
            <value>
                <fullName>Principal Place of Business - Address Proof</fullName>
            </value>
            <value>
                <fullName>Registered office - Address Proof</fullName>
            </value>
            <value>
                <fullName>Address Proof (Residential)</fullName>
            </value>
            <value>
                <fullName>Audit Report (with schedules)</fullName>
            </value>
            <value>
                <fullName>Bank Statement</fullName>
            </value>
            <value>
                <fullName>DOB Proof</fullName>
            </value>
            <value>
                <fullName>Financials - P&amp;L and BL</fullName>
            </value>
            <value>
                <fullName>Form 16</fullName>
            </value>
            <value>
                <fullName>Form 26 AS</fullName>
            </value>
            <value>
                <fullName>Form 60</fullName>
            </value>
            <value>
                <fullName>GST Returns</fullName>
            </value>
            <value>
                <fullName>Identity Proof</fullName>
            </value>
            <value>
                <fullName>Income Tax Returns</fullName>
            </value>
            <value>
                <fullName>Increments/ Appraisal Letter</fullName>
            </value>
            <value>
                <fullName>ITR Computation</fullName>
            </value>
            <value>
                <fullName>Non Individual Documents</fullName>
            </value>
            <value>
                <fullName>Own house / office ownership proof</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>Payslip</fullName>
            </value>
            <value>
                <fullName>Photograph</fullName>
            </value>
            <value>
                <fullName>Property Papers</fullName>
            </value>
            <value>
                <fullName>Qualification proof</fullName>
            </value>
            <value>
                <fullName>Relationship proof</fullName>
            </value>
            <value>
                <fullName>Rental Income Proof</fullName>
            </value>
            <value>
                <fullName>Repayment Documents</fullName>
            </value>
            <value>
                <fullName>Sanction Letter of OD/ CC</fullName>
            </value>
            <value>
                <fullName>Signature Verification Proof</fullName>
            </value>
            <value>
                <fullName>Residence Address proof - OVD</fullName>
            </value>
            <value>
                <fullName>Residence Address proof - Deemed OVD</fullName>
            </value>
            <value>
                <fullName>Sanction Letter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Fileuploadcttrl_Test.cls
@isTest
public class Fileuploadcttrl_Test {
    
 @testsetup
    Public static void insertDocumentDeatil(){
       LoanAppl__c loanApp = TestDataFactory.createLoanApplication(True); 
       Applicant__c applicant = TestDataFactory.createSingleApplicant(True,loanApp.Id);
       DocMstr__c docMaster = TestDataFactory.DocumentMasterData(True);
       DocDtl__c docDtl = TestDataFactory.createDocumentDetail(True,'Test',applicant.Id,docMaster.Id);
       docDtl.DocTyp__c = 'Sanction Letter';
       docDtl.IsLatest__c = true;
       docDtl.ValidityDays__c = -5;
       docDtl.LAN__c = loanApp.Id; 
       TriggerBase.bypass('Case');
       Update docDtl;
       TriggerBase.clearBypass('Case');        
    }
    
    @isTest
    Public static void test_fetchFiles(){
      List<DocDtl__c> lstDocdtl = [SELECT ID,DocTyp__c,IsLatest__c,ValidityDays__c FROM DocDtl__c WHERE  DocTyp__c = 'Sanction Letter' ]; 
      system.assert(!lstDocdtl.isEmpty(),'document detail list should not empty');
      Fileuploadcttrl.fetchFiles(lstDocdtl[0].Id);
    }

}