force-app/main/default/objects/DocMstr__c/fields/DocTyp__c.field-meta.xml
<CustomField>
    <fullName>DocTyp__c</fullName>
    <label>DocumentType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Address Proof</fullName>
            </value>
            <value>
                <fullName>Principal Place of Business - Address Proof</fullName>
            </value>
            <value>
                <fullName>Registered office - Address Proof</fullName>
            </value>
            <value>
                <fullName>Address Proof (Residential)</fullName>
            </value>
            <value>
                <fullName>Audit Report (with schedules)</fullName>
            </value>
            <value>
                <fullName>Bank Statement</fullName>
            </value>
            <value>
                <fullName>DOB Proof</fullName>
            </value>
            <value>
                <fullName>Financials - P&amp;L and BL</fullName>
            </value>
            <value>
                <fullName>Form 16</fullName>
            </value>
            <value>
                <fullName>Form 26 AS</fullName>
            </value>
            <value>
                <fullName>Form 60</fullName>
            </value>
            <value>
                <fullName>GST Returns</fullName>
            </value>
            <value>
                <fullName>Identity Proof</fullName>
            </value>
            <value>
                <fullName>Income Tax Returns</fullName>
            </value>
            <value>
                <fullName>Increments/ Appraisal Letter</fullName>
            </value>
            <value>
                <fullName>ITR Computation</fullName>
            </value>
            <value>
                <fullName>Non Individual Documents</fullName>
            </value>
            <value>
                <fullName>Own house / office ownership proof</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>Payslip</fullName>
            </value>
            <value>
                <fullName>Photograph</fullName>
            </value>
            <value>
                <fullName>Property Papers</fullName>
            </value>
            <value>
                <fullName>Qualification proof</fullName>
            </value>
            <value>
                <fullName>Relationship proof</fullName>
            </value>
            <value>
                <fullName>Rental Income Proof</fullName>
            </value>
            <value>
                <fullName>Repayment Documents</fullName>
            </value>
            <value>
                <fullName>Sanction Letter of OD/ CC</fullName>
            </value>
            <value>
                <fullName>Signature Verification Proof</fullName>
            </value>
            <value>
                <fullName>Residence Address proof - OVD</fullName>
            </value>
            <value>
                <fullName>Residence Address proof - Deemed OVD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReusableLookupController.cls
public without sharing class ReusableLookupController {
    @AuraEnabled(cacheable=true)
    public static List<ResultWrapper> fetchRecords(SearchWrapper inputWrapper) {
        Map<String, ResultWrapper> resultMap = new Map<String, ResultWrapper>();
        try {
            if (inputWrapper != null) {
                String fieldsToQuery = 'SELECT Id, ';
                if (string.isNotBlank(inputWrapper.fieldApiName)) {
                    fieldsToQuery = fieldsToQuery + inputWrapper.fieldApiName;
                }


                if (string.isNotBlank(inputWrapper.selectFields)) {
                    fieldsToQuery =
                        fieldsToQuery +
                        ',' +
                        inputWrapper.selectFields;
                }
                String query =
                    fieldsToQuery +
                    ' FROM ' +
                    inputWrapper.objectApiName;

                String filterCriteria =
                    inputWrapper.fieldApiName +
                    ' LIKE ' +
                    '\'%' +
                    String.escapeSingleQuotes(
                        inputWrapper.searchString.trim()
                    ) +
                    '%\'';

                system.debug('input wrapper ' + inputWrapper);
                if (string.isNotBlank(inputWrapper.filterConditions)) {
                    filterCriteria += ' AND ' + inputWrapper.filterConditions;
                }
                if (String.isNotBlank(inputWrapper.selectedRecordId)) {
                    if (String.isNotBlank(inputWrapper.selecetdFieldName)) {
                        query +=
                            ' WHERE ' +
                            inputWrapper.selecetdFieldName +
                            ' = \'' +
                            inputWrapper.selectedRecordId +
                            '\'';
                    } else {
                        query +=
                            ' WHERE Id = \'' +
                            inputWrapper.selectedRecordId +
                            '\'';
                    }
                } else if (
                    String.isNotBlank(inputWrapper.parentFieldApiName) &&
                    String.isNotBlank(inputWrapper.parentRecordId)
                ) {
                    query +=
                        ' WHERE ' +
                        inputWrapper.parentFieldApiName +
                        ' = \'' +
                        inputWrapper.parentRecordId +
                        '\'';
                    query += ' AND ' + filterCriteria;
                } else {
                    query += ' WHERE ' + filterCriteria;
                }
                List<ResultWrapper> returnWrapperList = new List<ResultWrapper>();
                //Adding limit Manish P
                query =
                    query +
                    ' Order BY ' +
                    inputWrapper.fieldApiName +
                    ' LIMIT 5000';

                system.debug('query:::::::>' + query);
                for (SObject s : Database.query(query)) {
                    ResultWrapper wrap = new ResultWrapper();
                    wrap.record = s;
                    
                    if (inputWrapper.fieldApiName.contains('__r')) {
                        //string filedApiName = inputWrapper.fieldApiName.replace('__r','');
                        list<string> fieldNames = inputWrapper.fieldApiName.split(
                            '\\.'
                        );
                        system.debug(s.getSobject(fieldNames[0]));
                        wrap.mainField = (String) s.getSobject(fieldNames[0])
                            .get(fieldNames[1]);
                        
                    } else {
                        wrap.mainField = (String) s.get(
                            inputWrapper.fieldApiName
                        );
                    }
                    // if(inputWrapper.objectApiName.contains('TeamHierarchy__c')){
                    //     wrap.role = (String) s.get('EmpRole__c');
                    // }
                    //wrap.subField = (String)s.get(inputWrapper.otherFieldApiName
                    if (string.isNotBlank(inputWrapper.keyId)) {
                        if (inputWrapper.keyId.contains('__r')) {
                            list<string> keyIdList = inputWrapper.keyId.split(
                                '\\.'
                            );

                            wrap.id = (String) s.getSobject(keyIdList[0])
                                .get(keyIdList[1]);
                        } else {
                            wrap.id = (String) s.get(inputWrapper.keyId);
                        }
                    } else {
                        wrap.id = (String) s.get('id');
                    }
                    if (
                        inputWrapper.fieldApiName == 'DocTyp__c' &&
                        inputWrapper.objectApiName == 'DocMstr__c'
                    ) {
                        resultMap.put(wrap.mainField, wrap);
                    } else {
                        resultMap.put(wrap.id, wrap);
                        //resultMap.put(wrap.role,wrap);
                    }

                    if(resultMap.size() == 200) {
                        break;
                    }
                }
                return resultMap.values();
            }
            return null;
        } catch (Exception err) {
            system.debug(
                'Error Msg' +
                (err.getMessage() +
                'Line Number::::>' +
                err.getLineNumber())
            );
            throw new AuraHandledException(err.getMessage());
        }
    }

    public class ResultWrapper {
        @AuraEnabled
        public String mainField { get; set; }
        // @AuraEnabled public String subField{get;set;}
        @AuraEnabled
        public String id { get; set; }
        @AuraEnabled
        public SObject record { get; set; }
    }

    public class SearchWrapper {
        @AuraEnabled
        public String objectApiName { get; set; }
        @AuraEnabled
        public String fieldApiName { get; set; }
        //  @AuraEnabled public String otherFieldApiName{get;set;}
        @AuraEnabled
        public String searchString { get; set; }
        @AuraEnabled
        public String selectedRecordId { get; set; }
        @AuraEnabled
        public String parentRecordId { get; set; }
        @AuraEnabled
        public String parentFieldApiName { get; set; }
        @AuraEnabled
        public String filterConditions { get; set; }
        @AuraEnabled
        public String selectFields { get; set; }
        @AuraEnabled
        public String keyId { get; set; }
        @AuraEnabled
        public String selecetdFieldName { get; set; }
    }
}